# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='admin.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x61\x64min.proto\"\t\n\x07GetOpts\"\x17\n\x04Opts\x12\x0f\n\x07options\x18\x01 \x01(\t\"\x1c\n\x06SetOpt\x12\x12\n\njson_patch\x18\x01 \x01(\t\".\n\x0cSetOptResult\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x08LogEntry\x12\x0f\n\x07message\x18\x01 \x01(\t\"v\n\rServerMessage\x12\x15\n\x04opts\x18\x01 \x01(\x0b\x32\x05.OptsH\x00\x12\'\n\x0eset_opt_result\x18\x02 \x01(\x0b\x32\r.SetOptResultH\x00\x12\x1e\n\tlog_entry\x18\x03 \x01(\x0b\x32\t.LogEntryH\x00\x42\x05\n\x03msg\"P\n\rClientMessage\x12\x1c\n\x08get_opts\x18\x01 \x01(\x0b\x32\x08.GetOptsH\x00\x12\x1a\n\x07set_opt\x18\x02 \x01(\x0b\x32\x07.SetOptH\x00\x42\x05\n\x03msgb\x06proto3'
)




_GETOPTS = _descriptor.Descriptor(
  name='GetOpts',
  full_name='GetOpts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=24,
)


_OPTS = _descriptor.Descriptor(
  name='Opts',
  full_name='Opts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='options', full_name='Opts.options', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=49,
)


_SETOPT = _descriptor.Descriptor(
  name='SetOpt',
  full_name='SetOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_patch', full_name='SetOpt.json_patch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=79,
)


_SETOPTRESULT = _descriptor.Descriptor(
  name='SetOptResult',
  full_name='SetOptResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='SetOptResult.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='SetOptResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=127,
)


_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='LogEntry.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=156,
)


_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opts', full_name='ServerMessage.opts', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_opt_result', full_name='ServerMessage.set_opt_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_entry', full_name='ServerMessage.log_entry', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='ServerMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=158,
  serialized_end=276,
)


_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_opts', full_name='ClientMessage.get_opts', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_opt', full_name='ClientMessage.set_opt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='ClientMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=278,
  serialized_end=358,
)

_SERVERMESSAGE.fields_by_name['opts'].message_type = _OPTS
_SERVERMESSAGE.fields_by_name['set_opt_result'].message_type = _SETOPTRESULT
_SERVERMESSAGE.fields_by_name['log_entry'].message_type = _LOGENTRY
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['opts'])
_SERVERMESSAGE.fields_by_name['opts'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['set_opt_result'])
_SERVERMESSAGE.fields_by_name['set_opt_result'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_SERVERMESSAGE.oneofs_by_name['msg'].fields.append(
  _SERVERMESSAGE.fields_by_name['log_entry'])
_SERVERMESSAGE.fields_by_name['log_entry'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['msg']
_CLIENTMESSAGE.fields_by_name['get_opts'].message_type = _GETOPTS
_CLIENTMESSAGE.fields_by_name['set_opt'].message_type = _SETOPT
_CLIENTMESSAGE.oneofs_by_name['msg'].fields.append(
  _CLIENTMESSAGE.fields_by_name['get_opts'])
_CLIENTMESSAGE.fields_by_name['get_opts'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['msg']
_CLIENTMESSAGE.oneofs_by_name['msg'].fields.append(
  _CLIENTMESSAGE.fields_by_name['set_opt'])
_CLIENTMESSAGE.fields_by_name['set_opt'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['GetOpts'] = _GETOPTS
DESCRIPTOR.message_types_by_name['Opts'] = _OPTS
DESCRIPTOR.message_types_by_name['SetOpt'] = _SETOPT
DESCRIPTOR.message_types_by_name['SetOptResult'] = _SETOPTRESULT
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOpts = _reflection.GeneratedProtocolMessageType('GetOpts', (_message.Message,), {
  'DESCRIPTOR' : _GETOPTS,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:GetOpts)
  })
_sym_db.RegisterMessage(GetOpts)

Opts = _reflection.GeneratedProtocolMessageType('Opts', (_message.Message,), {
  'DESCRIPTOR' : _OPTS,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:Opts)
  })
_sym_db.RegisterMessage(Opts)

SetOpt = _reflection.GeneratedProtocolMessageType('SetOpt', (_message.Message,), {
  'DESCRIPTOR' : _SETOPT,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:SetOpt)
  })
_sym_db.RegisterMessage(SetOpt)

SetOptResult = _reflection.GeneratedProtocolMessageType('SetOptResult', (_message.Message,), {
  'DESCRIPTOR' : _SETOPTRESULT,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:SetOptResult)
  })
_sym_db.RegisterMessage(SetOptResult)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)


# @@protoc_insertion_point(module_scope)
