language: python
python:
  - "3.7"
stages:
  - execute

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: execute
      name: "Starting the Server"
      script: python start_server.py