- area: Chaos
  background: AACourtHD
  bglock: true
  evidence_mod: FFA
  locking_allowed: false
  iniswap_allowed: true
- area: Cases
  background: AACourtHD
  bglock: true
  evidence_mod: CM
  locking_allowed: false
  iniswap_allowed: true
