- 9991stClassCabinA
- 9991stClassCabinB
- 9992ndClassCabin
- 999Apartment
- 999CaptainsQuarters
- 999Cargo
- 999Casino
- 999Cdeck
- 999CentralStairs
- 999Chapel
- 999Chart
- 999Confinement
- 999DoorsA
- 999DoorsB
- 999Hospital
- 999Kitchen
- 999Library
- 999Operating
- 999Shower
- 999Steam
- 999Steeldoor
- 999Study
- 999Torture
- AABluecorp
- AACourt
- AACourtAnime
- AACourtChristmasDecorations
- AACourtChristmasLights
- AACourtHD
- AADefendantLobby
- AADefendantLobbyHD
- AADetentionCenter
- AAEdgeworthOffice
- AAGantOffice
- AAGatewaterHotel
- AAGlobalStudiosEast
- AAGlobalStudiosWest
- AAGourdLake
- AAGrossbergOffice
- AAI2Circus
- AAI2City
- AAI2GourdLake
- AAI2LogicChess
- AAI2MuseumPast
- AAI2MuseumPresent
- AAI2PIC
- AAI2Prison
- AAICohdopianEmbassy
- AAICourt
- AAICourtFlipped
- AAIEdgeworthOffice
- AAIGatewaterLandStage
- AAIGatewaterLandWildWest
- AAIiFlyAirlines
- AAParkingLot
- AAPoliceStation
- AATrainStation
- AAWrightOffice
- AJBorschtBowlClub
- AJCourt
- AJCourtBirthday
- AJCourtHalloween
- AJCourtNight
- AJCourtTV
- AJDefendantLobby
- AJDetentionCenter
- AJDrewStudio
- AJHottiClinic
- AJKlavierOffice
- AJKristophCell
- AJMeraktisClinic
- AJPeoplePark
- AJSunshineColiseum
- AJWrightOffice
- Blackout
- custom
- custom1
- custom10
- custom2
- custom3
- custom4
- custom5
- custom6
- custom7
- custom8
- custom9
- CVStMystere
- DDCourt
- DDCourtGray
- DDCourtRuined
- DDCourtRuinedInvestigation
- DDCourtThemis
- DDDefendantLobby
- DDGyaxa
- DDNinetailsVale
- DDShipshapeAquarium
- DDThemisAcademy
- DGSCourtJapanese
- DGSCourtOldBailey
- DGSCourtOldBaileyJury
- DGSDefendantLobbyJapanese
- DGSDefendantLobbyOldBailey
- DGSLondon
- DRClassTrial
- JFAAirport
- JFABerryBigCircusEast
- JFABerryBigCircusWest
- JFAGatewaterHotel
- JFAHottiClinic
- JFAKurainVillage
- JFAMattHouse
- LBCastle
- LBMisc
- LBScotlandYard
- OCArcade
- OCBebop
- OCCourtCafe
- OCCourtCounty
- OCCourtCruise
- OCCourtEndless
- OCCourtFinalDestination
- OCCourtInverted
- OCCourtPirateShip
- OCCourtSky
- OCCourtSpace
- OCCourtSpaceShip
- OCCourtTouhou
- OCCourtZetta
- OCDungeon
- OCHospital
- OCRoad
- OCTownPirate
- OCTownShanty
- OCWhiteRoom
- P4Ubaseball
- P4UBasement
- P4Ubeach
- P4Ubuilding
- P4Uconcert
- P4Ugarden
- P4Ugraveyard
- P4Uhell
- P4Ujail
- P4ULab
- P4Umisc
- P4Unight
- P4Uoffices
- P4Urailway
- P4Urestaurants
- P4Urooms
- P4Uruins
- P4Uschool
- P4Ustage1
- P4Ustage2
- P4Ustation
- P4Ustore
- P4Utent
- P4Utransport
- P4Utv
- P4Uvelvetroom
- PLvsAAAlchemistHouse
- PLvsAABellTower
- PLvsAACastle
- PLvsAACourtEnglish
- PLvsAACourthouse
- PLvsAACourtLabyrinthia
- PLvsAADefendantLobbyEnglish
- PLvsAADefendantLobbyLabyrinthia
- PLvsAAEclaireBakery
- PLvsAAForest
- PLvsAAGreatArchive
- PLvsAALabyrinthiaInner
- PLvsAALabyrinthiaOuter
- PLvsAALondon
- PLvsAARougeTavern
- PLvsAARuins
- PLvsAAStorytellerTower
- PLvsAAWagon
- PLvsAAWorkshop
- SoJCourt
- SoJDefendantLobby
- TTAtmeyOffice
- TTBlueScreensInc
- TTDemasqueHideout
- TTHazakuraTemple
- TTHazakuraTempleInner
- TTKBSecurity
- TTLordlyTailor
- TTTenderLender
- TTTresBien
