- 1 Anonymous 
- 2 Anonymous 
- 3 Anonymous 
- 4 Anonymous 
- Ace 
- Acro 
- Adachi 
- Adam Ladyfirst 
- Adrian 
- Ahlbi 
- Aigis 
- Alfendi 
- Alita Tiala 
- Altamont 
- Andistandhin 
- Angel Starr 
- Miku Hatsune
- Nico Yazawa
- Apollo 
- ApolloSOJ 
- ApolloSoJWit 
- April 
- Archibald 
- Archibald Doctor 
- Armstrong 
- Athena DD Wit 
- Athena DD Wit School 
- AthenaCykesSOJ 
- Atmey 
- Aura 
- Bailiff 
- Bailiff GB 
- Bailiff JP 
- Barnham 
- Barok Z 
- Bellboy 
- Ben 
- Beppo 
- Betty de Famme 
- Bikini and Elise 
- Birdman 
- Birdman Leg 
- Blackquill 
- Blaise Debeste 
- Bonnie_Karin 
- Bonny de Famme 
- Bowl 
- Buddy 
- Butch Browning 
- Butz 
- ButzEdgeworth 
- Byrne 
- Cabanela 
- Caeser Villan 
- Cammy 
- Chelmey 
- Chiaki 
- Chrom 
- Cindy Law 
- Clover 
- Cody 
- Colias Palaeno 
- Connor 
- Conway Stern 
- Crab 
- Crogrey 
- Dahlia 
- Dane Gustavia 
- Dante 
- Darklaw 
- Daryan Crescend 
- Datz 
- de Killer 
- Decargo 
- Delicia 
- Deplume 
- Descole 
- Desiree 
- Dhurke 
- Dhurke D 
- Di-Jun Huang 
- Diego 
- Dio Brando
- Dmitri 
- Donnabella 
- Drebber 
- Drew 
- DrHotti 
- Elizabeth 
- Ema 
- EmaAJ 
- EmaSOJ 
- Emmy 
- Ernest Amano 
- Espella 
- Fawles 
- Filch 
- Flora 
- Franziska 
- Franziska AAI 
- Franziska AAI Young 
- Fulbright 
- Furio 
- Gant 
- Garan 
- Geiru 
- Gina Lestrade 
- Gina Lestrade Coat 
- Godot 
- Goulloyne 
- Gregory AAI 
- Grey 
- Grosky 
- Grossberg 
- Gumshoe 
- Gundam 
- Guy 
- Hajime 
- Haori 
- Hawk 
- Hobbes 
- Hobbes Def 
- Hosonaga 
- Hugh 
- Hutch Windibank 
- IbukiHD
- Ike 
- Inferno Cop 
- Inga 
- Ini 
- Iris 
- Iris Watson 
- Jay Elbird 
- Jeffrey Master 
- Jezail 
- Jinxie 
- Joan Garrideb 
- Joan Garrideb Juror 
- John Garrideb 
- John Marsh 
- Josephine
- Jotaro Kujo 
- Judge ET 
- Judge GB 
- Judge GK 
- Judge GK2 
- Judge JP 
- Judge Labyrinthia Edit 
- Judge's Bro 
- JudgeCalifornia 
- JudgeKhura'in 
- June 
- Juniper Casual 
- Juniper School 
- Junko
- Justine Courtney 
- Justine CourtneyPro
- Katherine Hall 
- Katrielle Layton 
- Kay 
- Kay Injured 
- Kazuma 
- Kazuma Assistant 
- Kazuma DGS2 
- Kazuma DGS2 Wit 
- Kazuma W 
- Kirigiri 
- Klavier 
- Klavier DD Wit 
- Knightley 
- Kokichi 
- Komaeda 
- Kristoph G 
- Kudo 
- Lamiroir 
- Lana 
- Lance Amano 
- Lauren Paups 
- Layton 
- Layton Inquisitor 
- Lbelle 
- LeTouse 
- Lisa 
- Long Lang 
- Lotta 
- Lotus 
- Lucina 
- Lucy Baker 
- Luke 
- Lynne 
- Machi Tobaye 
- Mae 
- Maggey 
- Makepeace 
- MakotoNaegi
- Manfred 
- Manfred AAI 
- Margaret 
- Marlon Rimes 
- Marshall 
- Marth
- Matilda 
- Matilda Headset 
- Matt 
- Max 
- Maya 
- MayaPLvsAA 
- MayaPLvsAA Co 
- MayaPLvsAA Co Knight 
- MayaSOJ 
- Means 
- Meekins 
- Megundal 
- Mia 
- Mia Young 
- Mikan 
- Miku Hatsune 
- Miles 
- MilesAAI 
- MilesSOJ 
- Missile 
- Moe 
- Monika
- Morgan 
- MrHat 
- Nahyuta 
- Naoto 
- Narcissus 
- Natsume 
- Neil 
- Nemmy Tinpillar 
- Nico Yazawa 
- Nicole Swift 
- Nikomina 
- Nikomina Hatless 
- O'Malley 
- O'Reil 
- Oldbag 
- Olga Orly 
- Orla 
- Oscar Fairplay 
- Oscar Fairplay Juror 
- Paolo 
- Patricia 
- Paul Atishon 
- Payne DGS 
- Payne DGS Wit 
- Payne Max 
- Payne SOJ 
- Payne Train
- Payne Train v2
- Pearl 
- PearlSOJ 
- Penny 
- Phoenix 
- Phoenix Counsel 
- Phoenix Hobo
- Phoenix PXZ2 
- Phoenix Young 
- PhoenixSOJ 
- Plum Kitaki 
- Polly 
- Ponco 
- Portsman 
- ProsecutorJustice 
- Q 
- Quercus Alba 
- Ranger Justice 
- Rayfa 
- Raymond Shields 
- Raymond Shields Young 
- Regina 
- Rhoda Teneiro 
- Rise 
- Roger Retinz 
- Ron 
- Roylott 
- Rozaic 
- Rydia 
- Ryu Leg 
- Ryutaro 
- Sahwit 
- Sailor 
- Sal 
- Santa 
- Sasha 
- Scuttlebutt 
- Sebastian 
- Seven 
- Sherlock 
- Sherlock Casual 
- Sherlock Goggled 
- Sherlock Undercover 
- SherlockWatson 
- Shih-na 
- Shiv 
- Sho 
- Simon 
- Sirhan Dogen 
- Sissel 
- Snake 
- Snow 
- Sonohigurashi 
- Spark 
- Stroganov 
- Susato 
- Susato Def 
- Susato hld 
- The King v2
- The Noid 
- Tobias Gregson 
- Trucy 
- Trucy SOJ 
- Trucy Young 
- Tully Tinpillar 
- Tyrell Badd 
- Uendo 
- Uzukamaru Taizo 
- Valant 
- Vasquez 
- Venus 
- Vera 
- Viola 
- Vortex 
- Warden 
- Wellington 
- Wesley Stickler 
- White 
- William 
- WillP 
- Winfred Kitaki 
- Wocky Kitaki 
- Yanni 
- Yew 
- Yu 
- Yuri 
- Yuujin Mikotoba 
- Yuujin Mikotoba Suit 
- Zak 
- Zinc Lablanc 
- 